"""empty message

Revision ID: 364469af0539
Revises: 4a8780856eee
Create Date: 2024-03-19 20:09:53.931007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364469af0539'
down_revision = '4a8780856eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('viewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('viewers', sa.Integer(), nullable=False),
    sa.Column('system_date_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['system_date_id'], ['system_dates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewers')
    # ### end Alembic commands ###
